### ISSUE TITLE
[META] Ideas 💡

### ISSUE THREAD

**Issue by moul** [moul/berty-library-test#2]
* [ ] add windows support
* [ ] work without `go mod -replace`
* [ ] be go-gettable
* [ ] tiny binary size
* [ ] tiny `depaware.txt`
